[gc]
model = "efficientnet-b0"
gradient_centralization = true
gradient_normalization = false
agc=false

[gc-agc]
model = "efficientnet-b0"
gradient_centralization = true
gradient_normalization = false
agc=true