[Base]
model = "efficientnet-b0"

[B1]
model = "efficientnet-b1"

[B2]
model = "efficientnet-b2"

[B3]
model = "efficientnet-b3"

[B4]
model = "efficientnet-b4"

[B5]
model = "efficientnet-b5"

[B6]
model = "efficientnet-b6"