[gc]
model = "efficientnet-b3"
gradient_centralization = true
gradient_normalization = false
agc=true

[gc-agc]
model = "efficientnet-b3"
gradient_centralization = true
gradient_normalization = true
agc=true